# Generated by Django 4.2.3 on 2023-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('currentlevel', models.CharField(max_length=80)),
                ('score', models.IntegerField()),
                ('time', models.CharField(max_length=80)),
            ],
        ),
    ]
